trading:
  max_position_size: 0.01
  max_daily_loss: 0.02
  risk_per_trade: 0.01
  min_confidence: 0.7

indicators:
  rsi_period: 14
  ema_period: 20
  macd_fast: 12
  macd_slow: 26
  macd_signal: 9

balance:
  min_required: 20.0 # Minimum balance required to trade in USDT
  reserve_percent: 20 # Keep this percentage as reserve
  max_position_percent: 30 # Maximum single position size as percentage

telegram:
  token: "8170894475:AAHRkjWwFa9vEXj-BnoWhsiRd_oJAjZzsxM"
  chat_id: "874994865" # Updated with your actual chat ID
  notifications:
    trades: true
    balance: true
    errors: true
